export enum City {
   // Thành phố trực thuộc Trung ương (6)
   HA_NOI = "Thành phố Hà Nội",
   HUE = "Thành phố Huế",
   DA_NANG = "Thành phố Đà Nẵng",
   CAN_THO = "Thành phố Cần Thơ",
   HAI_PHONG = "Thành phố Hải Phòng",
   HO_CHI_MINH = "Thành phố Hồ Chí Minh",

   // Tỉnh mới (28)
   LAI_CHAU = "Tỉnh Lai Châu",
   DIEN_BIEN = "Tỉnh Điện Biên",
   SON_LA = "Tỉnh Sơn La",
   LANG_SON = "Tỉnh Lạng Sơn",
   QUANG_NINH = "Tỉnh Quảng Ninh",
   THANH_HOA = "Tỉnh Thanh Hóa",
   NGHE_AN = "Tỉnh Nghệ An",
   HA_TINH = "Tỉnh Hà Tĩnh",
   CAO_BANG = "Tỉnh Cao Bằng",
   TUYEN_QUANG = "Tỉnh Tuyên Quang",
   LAO_CAI = "Tỉnh Lào Cai",
   THAI_NGUYEN = "Tỉnh Thái Nguyên",
   PHU_THO = "Tỉnh Phú Thọ",
   BAC_NINH = "Tỉnh Bắc Ninh",
   HUNG_YEN = "Tỉnh Hưng Yên",
   NINH_BINH = "Tỉnh Ninh Bình",
   QUANG_TRI = "Tỉnh Quảng Trị",
   QUANG_NGAI = "Tỉnh Quảng Ngãi",
   GIA_LAI = "Tỉnh Gia Lai",
   KHANH_HOA = "Tỉnh Khánh Hòa",
   LAM_DONG = "Tỉnh Lâm Đồng",
   DAK_LAK = "Tỉnh Đắk Lắk",
   DONG_NAI = "Tỉnh Đồng Nai",
   TAY_NINH = "Tỉnh Tây Ninh",
   VINH_LONG = "Tỉnh Vĩnh Long",
   DONG_THAP = "Tỉnh Đồng Tháp",
   CA_MAU = "Tỉnh Cà Mau",
   AN_GIANG = "Tỉnh An Giang",
}
export const CITY_TYPE_VALUES = Object.values(City) as City[];
